openapi: 3.2.0
info:
  version: 1.0.17
  title: AlayaCare Scheduler EVV API
  description: '**External IDs:**

    The following terms are used to reference ids that identify resources in systems external to AlayaCare:

    - client_id

    - employee_id

    - service_id

    - funder_id

    - visit_id

    - facility_id


    External IDs are required to be unique. No other assumptions are made regarding their format; they are treated as strings.


    **AlayaCare IDs:**

    The following terms are used to reference ids that identify resources in AlayaCare:

    - alayacare_client_id

    - alayacare_employee_id

    - alayacare_service_id

    - alayacare_funder_id

    - alayacare_visit_id

    - alayacare_facility_id


    **Remarks**

    All dates must be in ISO 8601 format with timezone data

    '
  contact:
    name: AlayaCare
servers:
- url: https://homecare.alayacare.ca/ext/api/v2/scheduler
tags:
- name: EVV
paths:
  /evv_visits:
    get:
      tags:
      - EVV
      summary: Get a list of evv visits
      description: Get a list of evv visits
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/count'
      - name: start_date_from
        in: query
        required: true
        description: '"Filter by visit start time greater or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-03T08:00:00-05:00`"

          '
        schema:
          type: string
          format: date-time
      - name: start_date_to
        in: query
        required: true
        description: 'Filter by visit start time less than or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-18T08:00:00-05:00`

          '
        schema:
          type: string
          format: date-time
      - name: created_date_from
        in: query
        required: false
        description: '"Filter by visit created time greater or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-03T08:00:00-05:00`"

          '
        schema:
          type: string
          format: date-time
      - name: created_date_to
        in: query
        required: false
        description: 'Filter by visit created time less than or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-18T08:00:00-05:00`

          '
        schema:
          type: string
          format: date-time
      - name: updated_date_from
        in: query
        required: false
        description: '"Filter by visit updated time greater or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-03T08:00:00-05:00`"

          '
        schema:
          type: string
          format: date-time
      - name: updated_date_to
        in: query
        required: false
        description: 'Filter by visit updated time less than or equal than specified value.

          Expected format is ISO 8601.

          Ex: `2018-02-18T08:00:00-05:00`

          '
        schema:
          type: string
          format: date-time
      - name: evv_status
        description: Status of the visit based on evv visit status hierarchy from AlayaCare web application
        in: query
        required: false
        schema:
          type: string
          enum:
          - scheduled
          - deleted
          - missed
          - approved
          - billed
      - name: evv_vendor
        description: Filter by funder evv vendor
        in: query
        required: false
        schema:
          type: string
          enum:
          - None
          - Sandata
          - eMedNY
          - Vesta
          - Tellus Rendered Services
          - hhax
      - $ref: '#/components/parameters/branch_id'
      - name: client_attributes
        description: Filter client attributes by name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: employee_attributes
        description: Filter employee attributes by name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: funder_attributes
        description: Filter funder attributes by name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: service_attributes
        description: Filter service attributes by name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: include
        description: Include extra information
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - diagnoses
      responses:
        '200':
          description: List of evv visits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EVVVisitList'
        '401':
          $ref: '#/components/responses/ErrorResponseAuthentication'
components:
  schemas:
    ErrorResponse:
      description: Error response
      type: object
      properties:
        code:
          type: integer
          example: 400
          description: Response code
        message:
          type: string
          example: Invalid request
          description: Detailed error message
      required:
      - code
      - message
    EVVVisit:
      type: object
      properties:
        alayacare_client_id:
          type: integer
          format: int64
          description: AlayaCare client ID
          example: 1001
        alayacare_employee_id:
          type:
          - integer
          - 'null'
          format: int64
          description: AlayaCare employee ID
          example: 101
        alayacare_funder_id:
          description: AlayaCare funder ID
          type: integer
          example: 1
        alayacare_funder_state:
          description: AlayaCare funder state
          type: string
          example: NY
        alayacare_service_id:
          type: integer
          format: int64
          description: AlayaCare service ID
          example: 1
        alayacare_visit_id:
          type: integer
          format: int64
          description: AlayaCare visit ID
          example: 10001
        bill_code:
          $ref: '#/components/schemas/EVVVisit_BillCode'
        cancelled:
          type: boolean
          description: Indicates if visit is cancelled
        cancel_code:
          $ref: '#/components/schemas/EVVVisit_CancelCode'
        client:
          $ref: '#/components/schemas/EVVVisit_Client'
        client_id:
          type:
          - string
          - 'null'
          description: External client ID
          example: sor_client_id_1
        created_by:
          type: string
          description: User who created the intervention in the visit
          example: system
        created_on:
          type: string
          format: date-time
          description: Visit created time (ISO 8601)
          example: '2017-07-08T13:30:00+00:00'
        employee:
          $ref: '#/components/schemas/EVVVisit_Employee'
        employee_id:
          type:
          - string
          - 'null'
          description: External employee ID
          example: sor_employee_id_1
        funder_id:
          type:
          - string
          - 'null'
          description: External funder ID
          example: sor_funder_id_1
        service_id:
          type:
          - string
          - 'null'
          description: External service ID
          example: sor_service_id_1
        visit_id:
          type:
          - string
          - 'null'
          description: External visit ID
          example: sor_visit_id_1
        status:
          type: string
          description: Status of the visit based on status hierarchy from AlayaCare web application.
          example: scheduled
          enum:
          - scheduled
          - vacant
          - on_hold
          - cancelled
          - offered
          - clocked
          - late
          - completed
          - missed
          - approved
        evv_status:
          type: string
          description: EVV status pf the visit
          example: scheduled
          enum:
          - scheduled
          - deleted
          - missed
          - approved
          - billed
        start_at:
          type: string
          format: date-time
          description: Visit start time (ISO 8601)
          example: '2017-07-08T13:30:00+00:00'
        end_at:
          type: string
          format: date-time
          description: Visit end time (ISO 8601)
          example: '2017-07-08T14:00:00+00:00'
        updated_by:
          type: string
          description: User who updated the visit
          example: system
        updated_on:
          type: string
          format: date-time
          description: Visit updated time (ISO 8601)
          example: '2017-07-08T13:30:00+00:00'
        timezone:
          type: string
          description: Timezone name in IANA format (iana.org/time-zones). If not set, returns the branch timezone.
          example: America/Toronto
        invoice_number:
          type: string
          description: master invoice number
        invoice_line_item_number:
          type: string
          description: invoice line number
        invoice_line_service_date:
          type: string
          description: invoice line service date
          example: '2022-01-01'
        invoice_line_trn:
          type: string
          description: The latest TRN of the invoice line
          example: '12345'
        invoice_line_units_billed:
          type: number
          description: invoice line units billed
          example: 8.5
        invoice_line_rate_by_billing_increment:
          type: number
          description: invoice line rate by billing increment
          example: 4.5
        invoice_line_billing_increment:
          type: integer
          description: invoice line billing increment
          example: 15
        invoice_total:
          type: string
          description: invoice total
        invoice_quantity:
          type: string
          description: invoice quantity
        invoice_quantity_units:
          type: string
          description: invoice quantity units
        invoice_unit_price:
          type: string
          description: invoice unit price
        claim_status:
          type: string
          description: status of the claim
        claim_update_flow:
          type: string
          description: The update flow of the claim, if claim is voided or revised.
          example: revise_and_resend
        funder:
          $ref: '#/components/schemas/EVVVisit_Funder'
        service:
          $ref: '#/components/schemas/EVVVisit_Service'
        work_sessions:
          type: array
          items:
            $ref: '#/components/schemas/EVVVisit_WorkSession'
        timekeeping:
          $ref: '#/components/schemas/EVVVisit_Timekeeping'
        notes:
          type: array
          items:
            $ref: '#/components/schemas/EVVVisit_Note'
        exceptions:
          type: array
          items:
            $ref: '#/components/schemas/EVVVisit_Exception'
        referring_provider:
          $ref: '#/components/schemas/EVVVisit_ReferringProvider'
        interventions:
          $ref: '#/components/schemas/EVVVisit_Interventions'
        authorizations:
          $ref: '#/components/schemas/EVVVisit_Authorizations'
        client_active_services:
          description: List of active Client Services linked to the same Sandata payer as the visit
          type: array
          items:
            $ref: '#/components/schemas/EVVVisit_ClientFunderActiveServiceSchema'
    EVVVisit_WorkSession:
      type: object
      description: Visit work session
      properties:
        clock_in:
          description: Work session start time
          type: string
          format: date-time
          example: '2017-07-08T13:30:00+00:00'
        clock_out:
          description: Work session end time
          type:
          - string
          - 'null'
          format: date-time
          example: '2017-07-08T14:30:00+00:00'
        clock_in_location:
          $ref: '#/components/schemas/Location'
        clock_out_location:
          $ref: '#/components/schemas/Location'
        clock_in_phone:
          description: Work session Phone with IVR
          type: string
          example: '+1454515475'
        clock_out_phone:
          description: Work session Phone with IVR
          type: string
          example: '+1454515475'
    EVVVisit_Funder:
      type: object
      properties:
        ac_id:
          type: string
          description: AlayaCare ID for display in-app
          example: AC000000024
        attributes:
          type: array
          description: Funder attributes
          items:
            $ref: '#/components/schemas/EVVVisit_Attribute'
          example:
          - tag: npi
            value: '1407958499'
          - tag: provider_api
            value: '1'
          - tag: aggregator_state
            value: GA
          - tag: evv_destination_state
            value: GA
          - tag: payer_id
            value: NJ_HZ
          - tag: payer_code
            value: NJHZ
          - tag: tax_id
            value: '767469540'
          - tag: provider_name
            value: KPE DBA INDIA
          - tag: plan_id
            value: '12345'
          - tag: provider_taxonomy_code
            value: '38382829'
          - tag: evv_vendor
            value: tellus_rs
          - tag: provider_id
            value: '317066193'
          - tag: business_entity_id
            value: '203542'
          - tag: hhax_payer_id
            value: '123456'
        address:
          type: string
          description: Funder address
        address_suite:
          type: string
          description: Funder address suite
        code:
          description: Funder code
          type: string
          example: IC-1
        city:
          type: string
          description: Funder address city
        description:
          description: Funder description
          type: string
        name:
          description: Funder name
          type: string
          example: Insurance Company
        pull_billing_data_from_visit_notes:
          description: True if is founder fetch the billing information from notes.
          type: boolean
          example: true
        state:
          type: string
          description: Funder address state
        zip:
          type: string
          description: Funder address zip
    EVVVisit_Employee:
      type: object
      properties:
        ac_id:
          type: string
          description: AlayaCare ID for display in-app
          example: AC000000024
        attributes:
          type: array
          description: Employee attributes
          items:
            $ref: '#/components/schemas/EVVVisit_Attribute'
          example:
          - tag: SSN
            value: '1407958499'
          - tag: registration_id
            value: '123'
          - tag: rendering_provider_npi
            value: 26NH18121900
          - tag: caregiver_type
            value: both
          - tag: start_date
            value: '2020-05-25'
        birthday:
          type: string
          description: Employee birthday
        email:
          type: string
          description: Employee email
        first_name:
          type: string
          description: Employee first name
          example: John
        gender:
          type: string
          description: Employee gender
        last_name:
          type: string
          description: Employee last name
          example: Smith
        phone:
          type: string
          description: Employee phone
        updated_by:
          type: object
          description: User who last updated the employee
          properties:
            id:
              type: integer
              example: 100
        updated_on:
          type: string
          format: date-time
          description: Datetime of last time the employee was updated
    EVVVisitList:
      allOf:
      - $ref: '#/components/schemas/PaginatedList'
      description: Paginated list of evv visits
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/EVVVisit'
    EVVVisit_Timekeeping:
      type: object
      description: It contains information related to the Visit Timekeeping object associated with the EVV Visit.
      properties:
        first_clock_in_time:
          type:
          - string
          - 'null'
          format: date-time
          description: This field will always have the first clock-in time from the visit work sessions, regardless if it was overwritten or not.
          example: '2017-07-08T14:30:00+00:00'
        last_clock_out_time:
          type:
          - string
          - 'null'
          format: date-time
          description: This field will always have the last clock-out time from the visit work sessions, regardless if it was overwritten or it's is null.
          example: '2017-07-08T15:30:00+00:00'
        adjusted_start_time:
          type:
          - string
          - 'null'
          format: date-time
          description: This field contains adjusted start time, if the end time isn't adjusted it will be populated with the first clock-in time, it will only be null if there's no worksession and no adjusted start time.
          example: '2017-07-08T14:30:00+00:00'
        adjusted_end_time:
          type:
          - string
          - 'null'
          format: date-time
          description: This field contains adjusted end time, if the end time isn't adjusted it will be populated with the last clock-out time, it will only be null if there's no worksession and no adjusted end time.
          example: '2017-07-08T15:45:00+00:00'
        is_adjusted_start_time:
          type: boolean
          description: It will be true if the start time is adjusted.
          example: false
        is_adjusted_end_time:
          type: boolean
          description: It will be true if the end time is adjusted.
          example: true
    EVVVisit_Exception:
      type: object
      properties:
        id:
          type: integer
          description: Visit exception ID
        created_on:
          type: string
          format: date-time
          description: Creation time of the visit exception
          example: '2017-07-08T13:30:00+00:00'
        code:
          type: string
          description: Exception type code
        category:
          type: string
          description: Exception type category
        name:
          type: string
          description: Exception type name
        is_acknowledged:
          type: boolean
          description: Exception has been acknowledged
          example: true
        status:
          type: string
          description: Visit exception status
        details:
          type: string
          description: Visit exception details
        comments:
          type: string
          description: Visit exception comments
        reason_code:
          type: string
          description: Visit exception reason code
        reason_name:
          type: string
          description: Visit exception reason name
        reason_category:
          type: string
          description: Visit exception reason category
        resolution_code:
          type: string
          description: Visit exception resolution code
        resolution_name:
          type: string
          description: Visit exception resolution name
        change_by:
          type: string
          description: Visit exception change made by
    Location:
      description: User location information
      type:
      - object
      - 'null'
      properties:
        lat:
          type: number
          description: latitude
          example: 45.518
        lng:
          type: number
          description: longitude
          example: -73.582
    EVVVisit_Diagnoses:
      type: object
      properties:
        code:
          type: string
          description: Diagnosis name
          example: A028
        is_primary:
          type: boolean
          description: Diagnosis is primary or not primary
          example: true
    EVVVisit_Interventions:
      type: object
      properties:
        name:
          type: string
          description: Visit's intervention name
          example: DINN
    EVVVisit_ClientFunderActiveServiceSchema:
      type: object
      properties:
        name:
          description: Service name
          type: string
          example: Wound Care
        status:
          description: Service Status
          type: string
          example: active
          enum:
          - active
          - discharged
          - on_hold
          - waiting_list
        start_date:
          description: Service start date
          type: string
          format: date-time
          example: '2021-07-08T13:30:00+00:00'
        projected_end_date:
          description: Projected end date
          type: string
          format: date-time
          example: '2022-07-08T13:30:00+00:00'
    EVVVisit_CancelCode:
      description: Visit cancellation code
      type:
      - object
      - 'null'
      properties:
        id:
          type: integer
          description: AlayaCare cancel code ID
          example: 1
        code:
          type: string
          description: Cancel code
          example: CLNT_REQ_RESCHEDULE
        description:
          type:
          - string
          - 'null'
          description: Cancel code description
          example: Client requested reschedule
        is_billable:
          type: boolean
          description: Cancel Code is billable or not billable
          example: true
      required:
      - id
      - code
      - is_billable
    EVVVisit_BillCode:
      type: object
      properties:
        code:
          type: string
          description: Bill code
          example: HSW
        description:
          type: string
          description: Bill code description
          example: HSW
        id:
          type: integer
          description: Bill code Id
        units:
          type: string
          description: Bill code units
        is_midnight_rule_applicable:
          type: boolean
          description: Whether or not the visits associated to this bill code will be split into two billable items in overnight schedules.
    PaginatedList:
      description: Base model of all paginated lists
      type: object
      properties:
        count:
          type: integer
          description: Number of items in the response
          example: 1
        page:
          type: integer
          description: Current page number
          example: 1
        total_pages:
          type: integer
          description: Total number of pages available
          example: 1
        items:
          type: array
          items:
            type: object
      required:
      - count
      - page
      - total_pages
      - items
    EVVVisit_Authorizations:
      type: object
      properties:
        authorization_number:
          type: string
          description: Authorization Number
          example: '123456789'
        member_number:
          type: string
          description: Member Number
          example: '123456789'
    EVVVisit_Note:
      type: object
      properties:
        created_on:
          type: string
          format: date-time
          description: Creation time of the note
          example: '2017-07-08T13:30:00+00:00'
        text:
          type: string
          description: Content of the visit note
          maxLength: 1000
          example: A sample visit note.
    EVVVisit_Attribute:
      type: object
      properties:
        tag:
          type: string
          description: Attribute tag
        value:
          type: string
          description: Attribute value
    EVVVisit_ReferringProvider:
      type: object
      properties:
        npi:
          type: string
          description: Referring Provider NPI
          example: '679363'
        first_name:
          type: string
          description: Referring Provider first name
        last_name:
          type: string
          description: Referring Provider last name
    EVVVisit_Client:
      type: object
      properties:
        ac_id:
          type: string
          description: AlayaCare ID for display in-app
          example: AC000000024
        address:
          type: string
          description: Client address
        address_suite:
          type: string
          description: Client address suite
        attributes:
          type: array
          description: Client attributes
          items:
            $ref: '#/components/schemas/EVVVisit_Attribute'
          example:
          - tag: country
            value: US
          - tag: email
            value: example@gmail.com
          - tag: member_id
            value: '1407958499'
          - tag: alternate_member_id
            value: 16795F4A6A5
          - tag: mcp_number
            value: '123456'
          - tag: jurisdiction_id
            value: '123456'
          - tag: medicare_id
            value: '123456789'
          - tag: newborn_indicator
            value: '0'
        birthday:
          type: string
          description: Client birthday
        city:
          type: string
          description: Client address city
        first_name:
          type: string
          description: Client first name
          example: John
        gender:
          type: string
          description: Employee gender
        last_name:
          type: string
          description: Client last name
          example: Smith
        phone:
          type: string
          description: Client phone
        phone_other:
          type: string
          description: Client other phone
        phone_personal:
          type: string
          description: Client personal phone
        state:
          type: string
          description: Client address state
        zip:
          type: string
          description: Client address zip
        timezone:
          type: string
          description: Timezone name in IANA format (iana.org/time-zones). If not set, returns the branch timezone.
          example: America/Toronto
        diagnoses:
          type: array
          description: Client diagnoses
          items:
            $ref: '#/components/schemas/EVVVisit_Diagnoses'
    EVVVisit_Service:
      type: object
      properties:
        name:
          description: Service name
          type: string
          example: Wound Care
        start_date:
          description: Service start date
          type: string
          format: date-time
          example: '2017-07-08T13:30:00+00:00'
        projected_end_date:
          description: Projected end date
          type: string
          format: date-time
          example: '2022-08-08T13:30:00+00:00'
        service_code_id:
          description: AlayaCare service code id
          type: integer
          example: 1
        service_code_name:
          description: AlayaCare service code name
          type: string
          example: WOUND-CARE
        attributes:
          type: array
          description: Client attributes
          items:
            $ref: '#/components/schemas/EVVVisit_Attribute'
          example:
          - tag: medicaid_prior_authorization_number
            value: '100'
        status:
          description: Service current status
          type: string
          example: active
          enum:
          - active
          - discharged
          - on_hold
          - waiting_list
  parameters:
    page:
      description: Filter by page number.
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
    branch_id:
      description: 'Filter by branch ID `(default: current user branch)`

        '
      name: branch_id
      in: query
      required: false
      schema:
        type: integer
    count:
      description: Number of items per page.
      name: count
      in: query
      required: false
      schema:
        type: integer
        default: 100
  responses:
    ErrorResponseAuthentication:
      description: Authorization required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 401
            message: Authorization required.
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
      description: Basic HTTP auth over https
